### ISSUE TITLE
Unparsable GIF

### ISSUE THREAD

**Issue by Pitometsu** [sksamuel/scrimage#174]
```scala
scala> com.sksamuel.scrimage.nio.ImageReader.fromPath(java.nio.file.Paths.get("/home/yuriypitomets/Downloads/po.gif"))
com.sksamuel.scrimage.ImageParseException: Unparsable image
  at com.sksamuel.scrimage.nio.ImageReader$.$anonfun$fromBytes$5(ImageReader.scala:40)
  at scala.Option.getOrElse(Option.scala:121)
  at com.sksamuel.scrimage.nio.ImageReader$.fromBytes(ImageReader.scala:40)
  at com.sksamuel.scrimage.nio.ImageReader$.fromStream(ImageReader.scala:30)
  at com.sksamuel.scrimage.nio.ImageReader$.$anonfun$fromPath$1(ImageReader.scala:24)
  at com.sksamuel.scrimage.Using.using(Using.scala:7)
  at com.sksamuel.scrimage.Using.using$(Using.scala:5)
  at com.sksamuel.scrimage.nio.ImageReader$.using(ImageReader.scala:14)
  at com.sksamuel.scrimage.nio.ImageReader$.fromPath(ImageReader.scala:23)
  ... 36 elided
```
![po](https://user-images.githubusercontent.com/2434691/49244053-8f46b100-f417-11e8-9a35-ab20a3e8af7d.gif)

**Comment by sksamuel** [comment]
Intellij can't open it either, so definitely something odd. But open-gif does support it, so I've added that to the parsers. Good catch!
