### ISSUE TITLE
Error: no awt in java.library.path

### ISSUE THREAD

**Issue by ikr0m** [sksamuel/scrimage#176]
I've received following error. It happens rarely. This time it happened after 13 times calling same method in 30 minutes. This method gets image bytes and rotates it if necessary then returns it. Method body looks like this:
```
val img = Image(arrayBytes)
val rotatedImage = if (img.ratio > 1) {
        img.rotateRight
      } else {
        img
      }
// other operations (flipping) on image if necessary
// val thumbnailBytes = rotatedImg.bytes
Ok(thumbnailBytes).as("image/jpeg")
```

```
Uncaught error from thread [xx-server-akka.actor.default-dispatcher-51164]: no awt in java.library.path, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[xx-server]
java.lang.UnsatisfiedLinkError: no awt in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at java.awt.Toolkit$3.run(Toolkit.java:1640)
at java.awt.Toolkit$3.run(Toolkit.java:1638)
at java.security.AccessController.doPrivileged(Native Method)
at java.awt.Toolkit.loadLibraries(Toolkit.java:1637)
at java.awt.Toolkit.<clinit>(Toolkit.java:1674)
at sun.awt.AppContext$2.run(AppContext.java:277)
at sun.awt.AppContext$2.run(AppContext.java:266)
at java.security.AccessController.doPrivileged(Native Method)
at sun.awt.AppContext.initMainAppContext(AppContext.java:266)
at sun.awt.AppContext.access$400(AppContext.java:135)
at sun.awt.AppContext$3.run(AppContext.java:321)
at sun.awt.AppContext$3.run(AppContext.java:304)
at java.security.AccessController.doPrivileged(Native Method)
at sun.awt.AppContext.getAppContext(AppContext.java:303)
at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:154)
at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
at com.sksamuel.scrimage.Image$.<init>(Image.scala:809)
at com.sksamuel.scrimage.Image$.<clinit>(Image.scala)
at controllers.xx.AppController.$anonfun$imgData$3(AppController.scala:232)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Error was thrown on this line:
```
// arrayByte is Array[Byte] type and contains JPEG image file bytes. JPG file size is 1.5MB
// Line 232
val img = Image(arrayByte)
```
Maybe this is because of memory issue. Same issue happened before and increased memory by adding following line to execution of jar file:
`-Dhttp.port=9000 -J-Xms1G -J-Xmx2G -J-server -J-XX:+ExitOnOutOfMemoryError`
At that time I was OutOfMemory error. Now I don't see this error on system log, but same application error `no awt in java.library.path`.

**Comment by vimalaguti** [comment]
maybe you're using an headless jre? try adding `-Djava.awt.headless=true`
