### ISSUE TITLE
Cannot transform some tiff images

### ISSUE THREAD

**Issue by atk91** [sksamuel/scrimage#194]
```
import java.io.File

import com.sksamuel.scrimage


object Main extends App {
  val in = new File("./src.tiff")
  val img = scrimage.ImmutableImage.loader().fromFile(in).cover(10, 10)
}
```
This fails on the following image: [src.tiff.gz](https://github.com/sksamuel/scrimage/files/4262616/src.tiff.gz)
(Github does not allow attaching *.tiff files, so that's *.tiff.gz, you need to uncompress it)

Stacktrace:
```[error] (run-main-b) java.lang.IllegalArgumentException: Unknown image type 0
[error] java.lang.IllegalArgumentException: Unknown image type 0
[error]         at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:501)
[error]         at com.sksamuel.scrimage.ImmutableImage.fromAwt(ImmutableImage.java:115)
[error]         at com.sksamuel.scrimage.ImmutableImage.wrapAwt(ImmutableImage.java:161)
[error]         at com.sksamuel.scrimage.ImmutableImage.scaleTo(ImmutableImage.java:1150)
[error]         at com.sksamuel.scrimage.ImmutableImage.cover(ImmutableImage.java:522)
[error]         at Main$.delayedEndpoint$Main$1(Main.scala:11)
[error]         at Main$delayedInit$body.apply(Main.scala:6)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:73)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:73)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
[error]         at scala.App.main(App.scala:73)
[error]         at scala.App.main$(App.scala:71)
[error]         at Main$.main(Main.scala:6)
[error]         at Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by sksamuel** [comment]
I've added a test for #194 and it seems to pass ok.
Are you include the scrimage-formats-extra module required for TIFFs ?

**Comment by atk91** [comment]
@sksamuel No, it has not been included, and including it fixes that issue, thank you!
But, that's quite confusing, because , `cover`ing `tiff`s still works on some tiffs without `scrimage-formats-extra`, example: [1.tiff.gz](https://github.com/sksamuel/scrimage/files/4288516/1.tiff.gz)

**Comment by sksamuel** [comment]
My guess would be that the built in java.io decoders don't support all formats of TIFF but the 12monkeys one that's included in formats extra does.
