### ISSUE TITLE
Cannot transform some png images

### ISSUE THREAD

**Issue by atk91** [sksamuel/scrimage#196]
Main.scala:
```
import java.io.File

import com.sksamuel.scrimage

object Main extends App {
  val in = new File("./src.png")
  val out = new File("./out.jpg")
  val img = scrimage.ImmutableImage.loader().fromFile(in).cover(100, 100).output(new scrimage.nio.JpegWriter, out)
}
```

build.sbt:
```
ThisBuild / scalaVersion := "2.12.10"
libraryDependencies += "com.sksamuel.scrimage" % "scrimage-core" % "4.0.0"
libraryDependencies += "com.sksamuel.scrimage" % "scrimage-filters" % "4.0.0"
libraryDependencies += "com.sksamuel.scrimage" %% "scrimage-scala" % "4.0.0"
libraryDependencies += "com.sksamuel.scrimage" % "scrimage-formats-extra" % "4.0.0"
```

Output:
```
[error] (run-main-0) java.lang.IllegalArgumentException: Unknown image type 0
[error] java.lang.IllegalArgumentException: Unknown image type 0
[error] 	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:501)
[error] 	at com.sksamuel.scrimage.ImmutableImage.fromAwt(ImmutableImage.java:115)
[error] 	at com.sksamuel.scrimage.ImmutableImage.wrapAwt(ImmutableImage.java:161)
[error] 	at com.sksamuel.scrimage.ImmutableImage.scaleTo(ImmutableImage.java:1154)
[error] 	at com.sksamuel.scrimage.ImmutableImage.cover(ImmutableImage.java:522)
[error] 	at com.sksamuel.scrimage.ImmutableImage.cover(ImmutableImage.java:496)
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:8)
[error] 	at Main$delayedInit$body.apply(Main.scala:5)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at Main$.main(Main.scala:5)
[error] 	at Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Full sbt project archive with image: [scrimage-test.zip](https://github.com/sksamuel/scrimage/files/4369045/scrimage-test.zip)
Extract it and do `sbt run` to reproduce the issue

**Comment by sksamuel** [comment]
Fixed in 4.0.1
