### ISSUE TITLE
Source and destination must store pixels as INT

### ISSUE THREAD

**Issue by badoualy** [sksamuel/scrimage#197]
Hi,

trying to compose two images, and i'm getting the following crash:

```
java.lang.IllegalStateException: Source and destination must store pixels as INT.

	at thirdparty.romainguy.BlendComposite$BlendingContext.compose(BlendComposite.java:113)
	at sun.java2d.loops.Blit$AnyBlit.Blit(Blit.java:179)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:960)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1015)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3408)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3384)
	at com.sksamuel.scrimage.composite.BlenderComposite.apply(BlenderComposite.java:23)
	at com.sksamuel.scrimage.composite.RedComposite.apply(RedComposite.java:5)
	at com.sksamuel.scrimage.ImmutableImage.composite(ImmutableImage.java:486)
```

Both images are png, also tried with jpeg, same issue.

Using this:
```kotlin
    private fun File.loadImage() = ImmutableImage.loader().fromFile(this)
    
    val masterImage = masterFile.loadImage()
    val actualImage = actualFile.loadImage()

    resultImage.output(imageWriter, setFiles.result) // Crash
```

Any clue?

I checked, the type is `Byte` instead of `Int`, not sure if I missed a conversion step?

**Comment by badoualy** [comment]
Using `ImmutableImage.loader().type(2)` did the trick
