### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Source and destination must store pixels as INT.

### ISSUE THREAD

**Issue by OpticFusion1** [sksamuel/scrimage#204]
This exception is thrown with the following filters
BackgroundBlendFilter
DissolveFilter
NashvilleFilter
OldPhotoFilter
SnowFilter
SummerFilter
VintageFilter

Exception:
Exception in thread "main" java.lang.IllegalStateException: Source and destination must store pixels as INT.
	at thirdparty.romainguy.BlendComposite$BlendingContext.compose(BlendComposite.java:113)
	at sun.java2d.loops.Blit$AnyBlit.Blit(Blit.java:179)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
	at com.sksamuel.scrimage.filter.BackgroundBlendFilter.apply(BackgroundBlendFilter.java:17)
	at optic_fusion1.imagetest.ImageTest.backgroundBlendFilter(ImageTest.java:69)
	at optic_fusion1.imagetest.ImageTest.main(ImageTest.java:24)

**Comment by sksamuel** [comment]
Do you have a sample image that triggers this ?

**Comment by OpticFusion1** [comment]
https://cdn.discordapp.com/avatars/172395749814960134/3fa1d56f2ff0d0e45d6181beeffffbd9.png

**Comment by OpticFusion1** [comment]
Any updates on this @sksamuel

**Comment by sksamuel** [comment]
I will look at this within the next week

**Comment by sksamuel** [comment]
Fixed in 4.0.6.
Thanks for the bug report.
