### ISSUE TITLE
Scrimage should output when webp is detected

### ISSUE THREAD

**Issue by xetra11** [sksamuel/scrimage#251]
I have a problem uploading the following image:

![IMG-20220410-WA0013](https://user-images.githubusercontent.com/8149023/164093318-14a676a6-314d-4ee9-b55d-1e6f10418c1b.jpg)

I am using the following scrimage version in my Kotlin backend service:
```
    implementation("com.sksamuel.scrimage:scrimage-core:4.0.31")
```

When uploading the mentioned image the following exception is thrown:
```
com.sksamuel.scrimage.ImageParseException: Image parsing failed. Tried the following ImageReader implementations:
com.sksamuel.scrimage.nio.ImageIOReader@2ba2a3f2 failed due to No javax.imageio.ImageReader supported this image format
com.sksamuel.scrimage.nio.PngReader@34dbb9f8 failed
com.sksamuel.scrimage.nio.OpenGifReader@5b1da868 failed due to Invalid GIF header.
at com.sksamuel.scrimage.nio.ImageReaders.read(ImageReaders.java:61) ~[scrimage-core-4.0.31.jar!/:na]
at com.sksamuel.scrimage.nio.ImageReaders.read(ImageReaders.java:34) ~[scrimage-core-4.0.31.jar!/:na]
at com.sksamuel.scrimage.nio.ImmutableImageLoader.load(ImmutableImageLoader.java:133) ~[scrimage-core-4.0.31.jar!/:na]
at com.sksamuel.scrimage.nio.ImmutableImageLoader.fromBytes(ImmutableImageLoader.java:100) ~[scrimage-core-4.0.31.jar!/:na]
at com.myapp.backend.service.ImageService.scaleImage(ImageService.kt:14) ~[classes!/:na]
at com.myapp.backend.service.GoogleStorageService.createSourceSets(GoogleStorageService.kt:39) ~[classes!/:na]
at com.myapp.backend.service.GoogleStorageService.saveItemImages(GoogleStorageService.kt:20) ~[classes!/:na]
at com.myapp.backend.api.GoogleStorageEndpoint.uploadItemImage(GoogleStorageEndpoint.kt:24) ~[classes!/:na]
```
*However this only happens on my mobile android device using the Chrome app*. When trying the same on my Mac M1 using Google Chrome and the Debuggers Mobile View Feature (Pixel 5 device) everything works as expected without any errors.

Here is the simplified callchain of the logic (I am omitting classes here and show all function calls as they were contained by one class):

```kt
@RestController
@RequestMapping("storage")
class GoogleStorageEndpoint @Autowired constructor(
    private val googleStorageService: GoogleStorageService,
    private val itemService: ItemService
) {
    @PostMapping("image/item/add")
    fun uploadItemImage(
        @RequestPart image: MultipartFile,
        @RequestParam itemId: String
    ) {
        val imageUrlSet = googleStorageService.saveItemImages(image.bytes, itemId)
        this.updateImageUrl(itemId, imageUrlSet)
    }

    fun saveItemImages(imageBytes: ByteArray, itemId: String): String {
        val sourceSets = this.createSourceSets(imageBytes)
        val fileName = UUID.randomUUID().toString()
        return sourceSets.keys.joinToString(";") {
            val blobName = this.createImage(itemId, fileName, it, sourceSets)
            "$CDN_HOST/$blobName"
        }
    }

    private fun createImage(itemId: String, fileName: String, width: Int, sourceSet: Map<Int, ByteArray>): String? {
        LOG.debug("Creating image for item $itemId with width $width")
        val blobId = BlobId.of(BUCKET, "items/$itemId/$fileName-p-$width")
        val blobInfo = BlobInfo.newBuilder(blobId).build()
        storage.create(blobInfo, sourceSet[width], Storage.BlobTargetOption.detectContentType())
        return blobId.name
    }

    private fun createSourceSets(imageBytes: ByteArray): Map<Int, ByteArray> {
        val sourceSet = mutableMapOf<Int, ByteArray>()
        with(sourceSet) {
            this[50] = this.scaleImage(imageBytes, 50).bytes(JpegWriter.Default)
            this[500] = this.scaleImage(imageBytes, 500).bytes(JpegWriter.Default)
            this[800] = this.scaleImage(imageBytes, 800).bytes(JpegWriter.Default)
            this[1080] = this.scaleImage(imageBytes, 1080).bytes(JpegWriter.Default)
            this[1600] = this.scaleImage(imageBytes, 1600).bytes(JpegWriter.Default)
        }
        return sourceSet.toMap()
    }
   
    // Error Source
    fun scaleImage(imageBytes: ByteArray, width: Int): ImmutableImage {
        return ImmutableImage.loader().fromBytes(imageBytes).scaleToWidth(width)
    }
}
```

Any idea what is happening here? The exception says no ImageReader is supporting "this" format but I have no clue what format is actually arriving at the endpoint?

Any tricks to log out the image file and analyse its content further to figure out what happened on the way from the Android device to the backend?

*EDIT*: I logged out the `MultipartFile` _contentType_ property to see if Android's Chrome is somewhat screwing up the upload content type. However the result was `image/jpeg`.

**Comment by xetra11** [comment]
I added a new log statement
```kt
LOG.info("detected image type: ${FormatDetector.detect(imageBytes)}")
```
that gave me this on Android Chrome
```
 detected image type: Optional[WEBP]
```
When using Mac M1 Chrome I receive this
```
 detected image type: Optional[JPEG]
```

**Comment by xetra11** [comment]
Ok after a quick research I figured out that I need the WEBP module for this to work.
https://sksamuel.github.io/scrimage/webp/

I think the exception should be more clear for this case. Scrimage can detect the WEBP image format (without any modules) so it should clearly tell the API user in the exception that the WEBP module is needed in order to have a successful image parsing. That's my suggestion.

**Comment by sksamuel** [comment]
That seems reasonable re: errors

**Comment by xetra11** [comment]
btw. please rate the cuteness of my dogs picture.

thanks

**Comment by sksamuel** [comment]
> btw. please rate the cuteness of my dogs picture.
> 
> thanks

10/10 :)

**Comment by CrackerKSR** [comment]
Is it working with Android? What is Android Chrome?

**Comment by sksamuel** [comment]
Scrimage now outputs:

```
Image parsing failed for WEBP. 
If the format is `webp` ensure you have a webp reader on your classpath, such as the `scrimage-webp` module.
```
